version: 2
updates:

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 6 5 */4 *"

  - package-ecosystem: "npm"
    directory: "/mapBuilder/www/js/"
    schedule:
      interval: "cron"
      cronjob: "0 6 5 */4 *"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 6 5 */4 *"
