name: ♻ Backport
on:
  pull_request_target:
    types:
      - closed

jobs:
  backport:
    runs-on: ubuntu-latest
    name: Backport
    steps:
      - name: Backport Bot
        id: backport
        uses: m-kuhn/backport@v1.2.7
        with:
          github_token: ${{ github.token }}
          add_labels: 'backport'
