name: StyleLint 🪄

on:
  push:
  pull_request:

jobs:
  eslint:
    name: "StyleLint 🎨‌"
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Install modules
        run: npm install

      - name: Run StyleLint
        run: npm run stylelint-fix
